apiVersion: v1
kind: Service
metadata:
  name: blobs-service
  labels:
    app: blobs
spec:
  selector:
    app: blobs
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP