apiVersion: v1
kind: Service
metadata:
  name: tukano-service
  labels:
    app: tukano
spec:
  selector:
    app: tukano
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort